openapi: 3.0.3

info:
  title: RaceDay API
  version: "0.9"


paths:

  /broadcasts:

    get:
      operationId: broadcastsGet

      summary: Retrieves broadcasts per the specified criteria. All parameters are optional.

      parameters:
        - name: event_id
          in: query
          description: An ID of an event for which to retrieve broadcasts.
          schema:
            type: string
            format: uuid
        - name: event_start
          in: query
          description: A UNIX timestamp indicating a particular date on which returned broadcasts must start.
          schema:
            type: number
            format: int64

      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Broadcast"
        "404":
          description: Event not found.

  /events:

    get:
      operationId: eventsGet

      summary: Retrieves events in the database for the specified date or dates.

      parameters:
        - name: window_start
          in: query
          description: A UNIX timestamp indicating a particular date on which returned events must start.
          schema:
            type: number
            format: int64
        - name: window_end
          in: query
          description: An optional UNIX timestamp indicating the end of a window in which returned events must start,
            where `window_start` indicates the beginning of the window. If not specified, only events that start on the
            date indicated by `window_start` will be returned.
          schema:
            type: number
            format: int64

      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"


components:

  schemas:

    Broadcast:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [ "Cable", "Facebook", "MotorTrend", "YouTube" ]
        url:
          type: string
      required:
        - id
        - type

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        start:
          type: number
          format: int64
        description:
          type: string
        location:
          $ref: "#/components/schemas/Location"
        series:
          $ref: "#/components/schemas/Series"
      required:
        - id
        - name

    Location:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name

    Series:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
