openapi: 3.0.3

info:
  title: RaceDay API
  version: "0.9"


paths:

  /events:

    get:
      operationId: eventsGet

      summary: Retrieves all events in the database.

      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"

  /streams:

    get:
      operationId: streamsGet

      summary: Retrieves all streams for the specified event.

      parameters:
        - name: event_id
          in: query
          description: The ID of the event for which to retrieve events.
          schema:
            type: string
            format: uuid

      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Stream"
        "404":
          description: Event not found.


components:

  schemas:

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        start:
          type: string
          format: date
        description:
          type: string
        location:
          $ref: "#/components/schemas/Location"
        series:
          $ref: "#/components/schemas/Series"
      required:
        - id
        - name

    Location:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name

    Series:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name

    Stream:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
      required:
        - id
        - url
