openapi: 3.0.3

info:
  title: RaceDay API
  version: "0.9"


paths:

  /events:

    get:
      operationId: eventsGet

      summary: Retrieves all events in the database.

      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"


components:

  schemas:

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
